### PR TITLE
Fix sqlite error field not found

### PR DESCRIPTION
**Pull request by rglonek**
Incorrect field names degined in Param section for model.

### CODE REVIEW

**Comment by thombashi** [comment]
@rglonek 
Could you explain why you thought those are incorrect field names?

**Comment by rglonek** [comment]
Ok, I think I am loosing my mind now. Previously when I tried to install this on a barebones docker container, it would show me an sqlite error field not found. a trace shown that the field names themselves were not accepted as valid by the sqlite module. I cannot replicate this now.

**Comment by nathan-muir** [comment]
@thombashi I get an error about this when trying to add two rules:

```$ tcdel enp0s3 --all
[INFO] delete enp0s3 qdisc
[INFO] delete enp0s3 ingress qdisc
[INFO] delete enp0s3 ifb device (ifb4618)
$ tcset enp0s3 --direction outgoing --src-port 3001  --rate 5Mbps --delay 150 --delay-distro 1
$ tcset enp0s3 --add --direction outgoing --src-port 27017 --rate 5Mbps  --delay 30  --delay-distro 4
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/simplesqlite/core.py", line 349, in execute_query
    result = self.connection.execute(str(query))
sqlite3.OperationalError: no such column: dst-network

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tcset", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/tcconfig/tcset.py", line 366, in main
    return TcSetMain(options).run()
  File "/usr/local/lib/python3.8/dist-packages/tcconfig/tcset.py", line 265, in run
    and TcShapingRuleFinder(logger=logger, tc=tc).is_exist_rule()
  File "/usr/local/lib/python3.8/dist-packages/tcconfig/_shaping_rule_finder.py", line 61, in is_exist_rule
    return self.find_parent() is not None
  File "/usr/local/lib/python3.8/dist-packages/tcconfig/_shaping_rule_finder.py", line 55, in find_parent
    for record in Filter.select(where=And(self.__get_filter_conditions())):
  File "/usr/local/lib/python3.8/dist-packages/simplesqlite/model.py", line 140, in select
    result = cls.__connection.select(
  File "/usr/local/lib/python3.8/dist-packages/simplesqlite/core.py", line 410, in select
    return self.execute_query(
  File "/usr/local/lib/python3.8/dist-packages/simplesqlite/core.py", line 355, in execute_query
    raise OperationalError(
simplesqlite.error.OperationalError
```

**Comment by rglonek** [comment]
@thombashi 
I can confirm, I do also get this before the change to the name:
```
[INFO] delete enp0s3 qdisc
[INFO] delete enp0s3 ingress qdisc
[INFO] delete enp0s3 ifb device (ifb4618)
$ tcset enp0s3 --direction outgoing --src-port 3001  --rate 5Mbps --delay 150 --delay-distro 1
$ tcset enp0s3 --add --direction outgoing --src-port 27017 --rate 5Mbps  --delay 30  --delay-distro 4
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/simplesqlite/core.py", line 349, in execute_query
    result = self.connection.execute(str(query))
sqlite3.OperationalError: no such column: dst-network
```

After this change, the error no longer occurs.

**Review by thombashi — APPROVED** [review]
Thank you for your additional information.
LGTM

**Pull request merged**
